logging:
  level:
    root: info

server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/api_doc?useUnicode=true&characterEncoding=UTF-8&useSSL=true&verifyServerCertificate=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
